version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock
    ports:
      - '5432:5432'
    volumes:
      - ./postgre-data-volume:/var/lib/postgresql/data